### ISSUE TITLE
Full screen video not respecting orientation lock

### ISSUE THREAD

**Issue by notdrone** [FrontendMasters/android-issues#1]
If a app is displaying a video in full screen, and I rotate the device to portrait, the video exits from full screen mode even when the orientation is locked

**Comment by DajoRamos** [comment]
Hi, I am also experiencing this issue every time i watch a video.

**Comment by dachev** [comment]
Thanks for the feedback. We have a fix in place. It will be released next week.

**Comment by dachev** [comment]
@notdrone @DajoRamos This has been fixed in 1.0.1
