### ISSUE TITLE
Bookmark sync issue

### ISSUE THREAD

**Issue by eeston** [FrontendMasters/android-issues#11]
Syncing bookmarks between web and android doesn't seem to work correctly.

Device: Pixel 2, Android P
1. Bookmark a course on the web
2. Go to bookmarks on the mobile app

Expected:
To see the course in the bookmarks section

Actual:
Some courses are there, but not all.

Further info:
Course name: JavaScript: From Fundamentals to Functional JS, v2
Shows as bookmarked if you manually search on android, but doesn't appear in bookmarked section.

**Comment by dachev** [comment]
@johneas10 This could be a client-side caching issue. Can you please restart the app and check one more time - it'd be very helpful.

Thanks,
Blago

**Comment by eeston** [comment]
Hi @dachev 

Tried restarting app.
Tried clearing cache & clearing storage then logging back in.

Same issue occurs,

**Comment by brentmn** [comment]
Hi @johneas10, this was an API issue. We just deployed a fix. Can you take a look?

**Comment by eeston** [comment]
Seems to be syncing correctly now. Thanks for the fix!
