### ISSUE TITLE
Allow Video (Audio) to Continue Playing in Background

### ISSUE THREAD

**Issue by markadrake** [FrontendMasters/android-issues#13]
**Feature Request**

When the Frontend Masters Android App (app) loses focus or context, I'd think that the audio from the currently playing video should still be played. Though it's probably covered in the statement above, shutting off the screen to my device should also allow the audio to continue playing.

I've really become accustomed to listening to podcasts and training videos in the background of my every day life - it's greatly increased how much content I can consume by listening to material in the car, at lunch, around the house. 

**Steps to Reproduce**

1. Open the app and begin playing any course.
2. (A) Switch to another app.
   - The currently playing video can no longer be heard.
   - Additionally, you may consider keeping the video on the screen inside a small box.
2. (B) Shut off the screen to your device.
   - The currently playing video can no longer be heard.

**Expected:**

I would like the video (or just audio) to continue playing even when the app loses context or focus. 

Note: I keep saying "play in the background" but it appears Android refers to this as the foreground (shame). This might serve as a reference: https://developer.android.com/guide/components/services#Foreground

**Comment by markadrake** [comment]
Hi @dachev,

I would like to follow up on this issue and see where it stands with the team at Frontend Masters. There's no code in this repo unfortunately, but if you were open to contributions I think I could devote some time to making this happen. 

I have some experience building cross platform apps in Xamarin, dabbled with iOS and Android for platform specific code where needed. It wouldn't hurt for me to jump in and at least try. 

Could you let me know if this was discussed / accepted / rejected?

Thanks and all the best,

**Comment by dachev** [comment]
Hi @markadrake,
Thank you for offering your help but unfortunately, we can't share the source code because the app is not open source.

We are wrapping up a series of new features due to be released in the next few weeks and when we are done with that we'll get together to plan our next steps.

I can assure you that this issue will be considered for development this fall/winter season.

Blago

**Comment by dachev** [comment]
This was implemented a few months ago
