### ISSUE TITLE
Video player stops playing after activating CC

### ISSUE THREAD

**Issue by jzabala** [FrontendMasters/android-issues#14]
### Preconditions

Device: BLU R1 HD, Android version 6.0
1. Connected to wifi
2. Logged in
3. Watching videos online. Not downloaded ones

### Steps to Reproduce
1. Start watching a video online. Not downloaded.
2. Tap CC
3. Change to another video. Not downloaded.

### Actual and Expected Result

**Expected:**
The video player should play the video and show the captions.

**Actual:**
The video player stops working and shows error: "An error occurred. Tap to retry."

### Additional Information
![image](https://user-images.githubusercontent.com/1315054/45886702-c9486680-bd87-11e8-80a3-6368fe8e51bb.png)

**Comment by dachev** [comment]
@brentmn This is ready for testing
