### ISSUE TITLE
Course progress is incorrect

### ISSUE THREAD

**Issue by notdrone-1** [FrontendMasters/android-issues#17]
The course progress in the app does not match the ones on the website
![screenshot_20181025-152502_frontend masters](https://user-images.githubusercontent.com/5713737/47492512-d1099800-d86a-11e8-8490-41721e19f84a.jpg)
I haven't started any of these courses yet. 
My guess is that the recycler view is recycling the progressbar for courses that haven't been started yet (no/`null` progress) as the progress shown for JS hard parts is the same as for complete intro to react.

**Comment by brentmn** [comment]
@notdrone, are you still seeing this issue? I've been testing from time to time but have not witnessed this behavior.

**Comment by notdrone-1** [comment]
Yes. Here a video that reproduces the issue: https://photos.app.goo.gl/BishdwePQSxCHwDm8
I haven't started the first three courses (which is shown correctly when I launch the app). But as I scroll back and forth, they pick up the progress of some random course.

**Comment by dachev** [comment]
@notdrone Thanks for the video. I think we have a pretty good idea what's causing this bug now. It will be fixed in the next release and we'll give you a heads up.

**Comment by notdrone-1** [comment]
working now. Thank you!
