### ISSUE TITLE
Auto-rotate video to the correct orientation when going horizontal (fullscreen)

### ISSUE THREAD

**Issue by dachev** [FrontendMasters/android-issues#18]
Currently, it always rotates left.

**Comment by HishamMubarak** [comment]
Another great feature I am looking for. Looking forward to it.
By the way, thanks for a great learning platform and an app to assist it.

**Comment by dachev** [comment]
Steps to reproduce:

 1. Play video in horizontal orientation, with the top of the phone pointing to the right
 2. Without changing the orientation, tap the exit fullscreen button to switch to portrait
 3. Without changing the orientation, tap the enter fullscreen button to switch to landscape

Expected: video is facing the user
Actual: Video is upside down

**Comment by dachev** [comment]
@brentmn this is ready for testing
