### ISSUE TITLE
Allow users to choose offline and streaming video bitrate

### ISSUE THREAD

**Issue by dachev** [FrontendMasters/android-issues#19]

**Comment by HishamMubarak** [comment]
Really looking forward to 480p or 360p support in mobile app.

**Comment by lokesh1729** [comment]
looking forward to this to change the quality/resolution manually

**Comment by Joshuafolorunsho** [comment]
This is really important. I'm on a limited plan right now. I would love to see more courses but I can't

**Comment by rishavbharti** [comment]
### It's been almost 1½ year since this feature was requested but still it hasn't been actioned upon.
Currently it seems that the video streams at 240p. _It becomes extremely difficult to read the code_. **Kindly provide an option to stream videos at higher resolution.**

**Comment by rishavbharti** [comment]
### It's been almost 1½ year since this feature was requested but still it hasn't been actioned upon.
The adaptive video streaming doesn't work well on my phone, it seems that the video streams at 240p. 
**_It becomes extremely difficult to read the code_.** **Kindly provide an option to stream videos at higher resolution.**

**Comment by Vansh1411** [comment]
> ### It's been almost 1½ year since this feature was requested but still it hasn't been actioned upon.
> The adaptive video streaming doesn't work well on my phone, it seems that the video streams at 240p.
> **_It becomes extremely difficult to read the code_.** **Kindly provide an option to stream videos at higher resolution.**

The only thing which is needed is video quality selection in settings so people can clearly see the code and quality of videos is according to the user. seriously not expecting this from frontend masters

**Comment by dachev** [comment]
This should be fully implemented as of v1.22.0
