### ISSUE TITLE
Lessons downloaded before CC made available do not display CC when CC made available

### ISSUE THREAD

**Issue by brentmn** [FrontendMasters/android-issues#22]
This is an edge case I ran into today. Often we release courses a day or two before the captions are made available. If a user downloads lessons when there are no captions available, those downloaded lessons fail to show the captions (or the CC button), even after the captions are made available.

Deleting the downloaded lessons, and re-watching, and even re-downloading, after the captions are made available solves the issue.

**Comment by KhaingThinzarliHtet** [comment]
This bug is still now.
