### ISSUE TITLE
Offline navigation

### ISSUE THREAD

**Issue by marpesia** [FrontendMasters/android-issues#25]
Case scenario: the subway without connection.

Actual:
Right now the app is trying to access to the server online in order to check my credentials or get the course info. So if I want to watch my downloaded videos I have to access to the course page before loose my connection. 

Expected:
It would be great to have offline navigation. If I'm already logged, store locally my data and courses in order to watch it without no connection.

**Comment by dachev** [comment]
Hi @marpesia. Thank you for the report. The app should allow you to navigate courses that have at least one download even when you are offline. Here is a video for reference: https://youtu.be/4AvObwj4x6c. Are you seeing something else on your device?

**Comment by marpesia** [comment]
Oh, that works!
I had the issue last month, in the subway.
The app keeps loading if I hadn't open the app previously. I also tested to open it before loose connection but had same issue in the general courses page. But now works.
I'll be watching in order to report any changes.
Thanks :)

**Comment by dachev** [comment]
@marpesia It might take a little longer if the network situation is more ambiguous, like in the subway, and the app thinks that it has a shot at loading fresh data, but it should scuttle the attempt and fall back to local data after 3 or 4 seconds. Let me know if anything changes or new information comes in.

**Comment by marpesia** [comment]
I guess I hadn't download any video from that specific course. I use to delete all after finish a course so it's possible not to have any download video at that moment.
