### ISSUE TITLE
Double tap to forward/rewind 

### ISSUE THREAD

**Issue by dachev** [FrontendMasters/android-issues#28]

**Comment by nbogie** [comment]
+1 to this.  It's really difficult on a phone to rewind a little.  The scrub bar at the bottom is very small and very inaccurate - where you might want to go back just 10 seconds you may end up being taken back many minutes, depending on the length of the section currently playing, and how fat your fingers are.

A "back-ten-seconds" button would also be ok but the UI is already overly small on phones so it'd be fiddly to use (Rewind is the second most common operation I'd make use of. Number one is simply pausing to take notes.)

**Comment by dachev** [comment]
Hi @nbogie. There should be skip/rewind buttons in the player controls. Do you see those on your phone? See the attached screenshot for reference.

![Screenshot_2021-01-07-13-29-20-59](https://user-images.githubusercontent.com/66780/103859634-f520bf00-50ec-11eb-9a79-0e53d2f02305.png)

**Comment by paragkatoch** [comment]
@dachev yeah it is there, but sometimes while clicking those I often click the buttons around them, which results in video change and when I come back to the video, then its starts from starting rather than where I left off.

**Comment by nbogie** [comment]
Hi, @dachev, yes, I see those and they'll do, thanks - not sure how I (presumably) missed them back in Jan!

**Comment by dachev** [comment]
@kristakoch 1.32.0 (538)

**Comment by dachev** [comment]
@kristakoch 1.32.0 (539)

**Comment by kristakoch** [comment]
@dachev, Downloaded the latest staging app. Working well for me!

It would be nice if there was a label under the arrows telling you how far and back you're going like the YouTube player does so you'd know it was a 10 second jump without needing to check the video timecode. Especially since you can skip without the video timecode being visible.

Side note: at first I expected that if I double tapped and kept my finger held down on the screen the video would play at 2x speed forward or back. Would be a nice addition, but seems like a separate feature.

**Comment by dachev** [comment]
@kristakoch 1.32.0 (540)

**Comment by kristakoch** [comment]
@dachev The 10sec label is helpful, and the skip is still working well! One more nice thing would be if you could see the video progress bar as you skip so you know how far into the video you've made it (I feel like when I use this feature I'll often do more than 1 skip to get to a specific part of the video).

**Comment by dachev** [comment]
@kristakoch Displaying the video progress alone will be challenging, and including other player controls like play/pause could unfortunately lead to a visual clash with the flashing skip indicators, which we want to avoid.
