### ISSUE TITLE
can´t login on Android 

### ISSUE THREAD

**Issue by andresmonterodev** [FrontendMasters/android-issues#29]
Issue Description

Device: Xiaomi Mi Note Pro, Android version 10
1. Connected to wifi and 4g as well
2. Logged in my phone browser on that account without problems

Steps to Reproduce

1. Log in
2. Only see a dismiss button, and nothing more happens
3. Logout browser on phone and laptop, nothing change
4. Reinstall app and clear cache, nothing change

Actual and Expected Result

Expected:
Login or shows the error code or something like that.

Actual:
Try to login and nothing happens only a dismiss button

Additional Information
 Screenshot
![Screenshot_2020-04-13-11-00-23-451_in mjg frontendmasters store](https://user-images.githubusercontent.com/53461001/79154379-6c633580-7d9d-11ea-930c-cbb57336de31.jpg)

**Comment by dachev** [comment]
Hello. Please email support@frontendmasters.com with your account details and we'll be happy to help you.

**Comment by andresmonterodev** [comment]
Yeah right, Chuck from Support try to help and send me to GitHub. Anyway,
thanks for You Now.

**Comment by dachev** [comment]
Sorry about the confusion. I'll take a look at the back end.

**Comment by andresmonterodev** [comment]
Nah don't worry, it should be a weird problem with Xiaomi Miui
customization layer. Mostly my issue report it's goes more to the lack of a
error display with that dismiss button.its tells you nothing about the
error, if it's password related, account doesn't exist, the backend dont
want a Chinese phone on that server, I don't know.


Thanks for your time

**Comment by dachev** [comment]
@codeagainst I see, thanks for the heads up. We'll fix that. I think you are unable to login because your device date/time is off. Can you make sure the time is correct and try again?

**Comment by andresmonterodev** [comment]
That's it, my home country has a very stupid change hour,against everyone,
and doesn't show me the correct hour if I setup automatically time setup,
but just enable and it's works ok.

Bye the way I see the error message with the dismiss button, kudos for that.

Thanks for your time ;)
