### ISSUE TITLE
show video annotations (links, errata like in web)

### ISSUE THREAD

**Issue by lokesh1729** [FrontendMasters/android-issues#30]
show video annotations (links, errata like in web) and notes

**Comment by dachev** [comment]
Hi @lokesh1729. Thank you for the feature request. We are planning to release the Notes functionality very soon so I'll edit the ticket to make it about annotations only.

**Comment by lokesh1729** [comment]
@dachev  : sure, but video annotations are very important than notes in my opinion

**Comment by dachev** [comment]
@lokesh1729 I am simply changing to ticket name to reflect the fact the notes functionality is already complete and we need to work on annotations.

**Comment by lokesh1729** [comment]
@dachev yes agreed on that but am saying that in my opinion you could have implemented or prioritised annotations than notes 😉

**Comment by dachev** [comment]
This was released a few months ago
