### ISSUE TITLE
Video player

### ISSUE THREAD

**Issue by cdking007** [FrontendMasters/android-issues#31]
There is some issue in video player of android app in latest version.
its cropping the video player on the full screen.
see below attachment of screen shot
![Screenshot_20200430-200709](https://user-images.githubusercontent.com/39514257/80728388-7f5b6100-8b24-11ea-80ec-2951dc0c9e6e.png)

**Comment by dachev** [comment]
We have also seen white padding on both sides of the player with some devices. This has been fixed and will be released soon.

**Comment by cdking007** [comment]
thank you :-)

**Comment by dachev** [comment]
@cdking007  This should be fixed now. Please download 1.10.1 and let us know if the problem persists.
