### ISSUE TITLE
Network Error when trying to access offline videos

### ISSUE THREAD

**Issue by bcye** [FrontendMasters/android-issues#32]
I've downloaded some offline videos. When I navigate via the sidebar to "offline courses" while disconnected to the internet it shows me a network error and a try again button.

Can I not access offline content without an internet connection?

**Comment by dachev** [comment]
Hello Bruce. Thanks for reporting this issue. We'll investigate and we'll let you know when we know more.

**Comment by dachev** [comment]
@bcye We have identified the issue and we are working to fix it. Thanks for your patience!

**Comment by dachev** [comment]
@bcye This should be fixed in the latest build that we released yesterday. Let us know if it's still not working.
