### ISSUE TITLE
Titlebar appears on fullscreen

### ISSUE THREAD

**Issue by djalilhebal** [FrontendMasters/android-issues#34]
Scenario:
- Start watching a video in fullscreen.
- A Messenger Chat Head appears.
- Android's titlebar appears and never goes away (even when the Chat Head is discarded).

Currently, the only way to "hide" it is to exit fullscreen mode and re-enter it.

**Additional information:**
- App version: 1.10.2
- Android version: 8.1

**Comment by dachev** [comment]
@djalilhebal I'm not sure I know what a Messenger Chat Head looks like. Would you be able to upload a screenshot or explain?

**Comment by djalilhebal** [comment]
Fullscreen, normal:
![Screenshots:Screenshot_20200515-163026](https://user-images.githubusercontent.com/32184973/82071583-37b10980-96ce-11ea-8fc2-34564db48301.jpg)

Fullscreen, interrupted. The titlebar appears:
![Screenshots:Screenshot_20200515-163750](https://user-images.githubusercontent.com/32184973/82071595-3bdd2700-96ce-11ea-8f6a-8134e991bc20.jpg)

The titlebar stays visible:
![Screenshots:Screenshot_20200515-163810](https://user-images.githubusercontent.com/32184973/82071600-3f70ae00-96ce-11ea-9bc7-80dbeb37facf.jpg)

**Comment by dachev** [comment]
Thank you @djalilhebal. We'll investigate.

**Comment by dachev** [comment]
@djalilhebal  This should be fixed now. Let us know if you are still experiencing this problem after upgrading to 1.10.3.
