### ISSUE TITLE
Full screen mode is not working anymore

### ISSUE THREAD

**Issue by SOG-web** [FrontendMasters/android-issues#35]
Before i updated the app to the new version i could use the full screen mode but after the update full screen mode did not work again 

Before update
![Screenshot_20200517-195422](https://user-images.githubusercontent.com/61606062/82157863-d9c22480-987b-11ea-876f-6c0779ae6a5d.png)

After update
![Screenshot_20200517-195132](https://user-images.githubusercontent.com/61606062/82157875-f52d2f80-987b-11ea-94cb-85a3714ac1e5.png)

Thanks

**Comment by dachev** [comment]
@SOG-web Thank you for reporting this. We are investigating.

**Comment by dachev** [comment]
@SOG-web What is your device and android version?

**Comment by SOG-web** [comment]
Android device

**Comment by dachev** [comment]
@SOG-web Can you share your device model number and android version?

**Comment by SOG-web** [comment]
model : Infinx X559C

Android version : 7.0

**Comment by SOG-web** [comment]
Hello

**Comment by dachev** [comment]
Thank you @SOG-web! We are investigating.

**Comment by dachev** [comment]
@SOG-web Can you upgrade to 1.10.3 and test if this is still happening. If so:

1) Does rotating your phone change the view orientation?
2) Does rotating your phone help bring the player fullscreen?
3) Does taping the fullscreen button (see the screenshot) help?

<img width="468" alt="Screen Shot 2020-05-20 at 7 50 04 PM" src="https://user-images.githubusercontent.com/66780/82447996-48e58600-9ad3-11ea-9397-7742d2ef2edd.png">

**Comment by SOG-web** [comment]
None of it is working

**Comment by SOG-web** [comment]
1. Yes
2. No, but whenever i put my phone on rotation and i rotate it to landscape, it still brings it n0t good, but when i rotate my phone back to portrait mode it brings full screen portrait but not full screen landscape

On landscape mode
![Screenshot_20200517-195132](https://user-images.githubusercontent.com/61606062/82484116-6154a100-9ad1-11ea-8f4e-b55bc993e748.png)

Back to portrait mode
![Screenshot_20200520-192416](https://user-images.githubusercontent.com/61606062/82484536-f5266d00-9ad1-11ea-92aa-3406a288e0ae.png)

3. No

**Comment by dachev** [comment]
@SOG-web We've identified the issue and we are working to fix it. Thanks for your patience.

**Comment by SOG-web** [comment]
no problem

**Comment by SOG-web** [comment]
Thanks, the new version update is working

**Comment by dachev** [comment]
For documentation purposes, this has been fixed in 1.10.5
