### ISSUE TITLE
Probable Resolution Issue

### ISSUE THREAD

**Issue by Tirnoch** [FrontendMasters/android-issues#39]
Device: Xiaomi Redmi Note 8 Plus, Android version 10
Preconditions:
Connected to wifi, logged in.

Steps to Reproduce:
Log in. Navigate to the professional part of the guided path and try to watch any video from the first two courses.

Expected:
Fullscreen mode working properly.

Actual:
The bottom right corner of the video, where total time sits, overflows the screen slightly.  The actual content is fully visible, but the full video time which is just after the time bar does not fit.

**Comment by dachev** [comment]
@Tirnoch this should be fixed in the latest release
