### ISSUE TITLE
Allow storing offline content on SD Card

### ISSUE THREAD

**Issue by elharony** [FrontendMasters/android-issues#4]
I noticed that the courses are downloaded directly to the Internal Storage.

There should be an option to select the Storage Location from:
1. Internal Storage
2. SD Card

As many users don't have enough Internal Space.

**Comment by dachev** [comment]
Hello from the team,

After debating the issue internally we agreed that it's important to allow storing downloads on external media. This will give Android users the freedom to save as much offline content as they desire, bypassing the capacity limitations imposed by their device.

However, we would have to protect the content from playback on unauthorized devices due to the following reasons:
  - it would be unfair to our instructors whose compensation is determined by playback stats
  - we would lose the ability to automatically fix errors and make updates which is essential in the fast-changing world of tech thus putting a strain on our support infrastructure and content quality

At this moment, we plan to allow storing videos offline on external media, but we can't commit to a precise timeline.

**Comment by DeepikaSharma5** [comment]
Are you still not allowing to store in SD card. I have a device with 128GB and 78 GB data of Front end Master. It is very difficult to use a separate device for Frontend master only.

**Comment by DeepikaSharma5** [comment]
> Hello from the team,
> 
> After debating the issue internally we agreed that it's important to allow storing downloads on external media. This will give Android users the freedom to save as much offline content as they desire, bypassing the capacity limitations imposed by their device.
> 
> However, we would have to protect the content from playback on unauthorized devices due to the following reasons:
>   - it would be unfair to our instructors whose compensation is determined by playback stats
>   - we would lose the ability to automatically fix errors and make updates which is essential in the fast-changing world of tech thus putting a strain on our support infrastructure and content quality
> 
> At this moment, we plan to allow storing videos offline on external media, but we can't commit to a precise timeline.

Are you still not allowing to store in SD card. I have a device with 128GB and 78 GB data of Front end Master. It is very difficult to use a separate device for Frontend master only.

**Comment by dachev** [comment]
@DeepikaSharma5 We haven't done any work on this yet but it's getting closer on our radar.

**Comment by zoneboy** [comment]
Can you please do this. I can't do anything useful with the internal memory download location. I have less than 2gb. How do you want me to learn.

**Comment by marcinmilewicz** [comment]
Seriously, it's absolutely weird that so great platform does not support offline storing on external devices. Most of chromebooks does not have enough internal storage. I believe it should be most prioritized feature. I regret that I bought second annual sub because I have not possibility to use it outside.

**Comment by MatkoKardum** [comment]
@dachev Hi, is there any updates on this, it would really help!

**Comment by dachev** [comment]
@MatkoKardum we released that as an experimental feature. You should be able to change the download location from the app settings. Let me know how it works, we would love to hear feedback. Thanks!

**Comment by MatkoKardum** [comment]
@dachev Well I tried now downloading a video but when feature is enabled I cant find it in Internal Storage, is this a bug?

**Comment by MatkoKardum** [comment]
@dachev Well I tried now downloading a video but when feature is enabled but cant find it in Internal Storage, is that a bug?

**Comment by MatkoKardum** [comment]
@dachev  or am I asking for different feature

**Comment by dachev** [comment]
@MatkoKardum are you able to play the course offline after it's downloaded?

**Comment by MatkoKardum** [comment]
@dachev Yes,but cant find it in my Files/Directories

**Comment by dachev** [comment]
@MatkoKardum did you select SD CARD in this screen?

<img width="461" alt="Screenshot 2023-01-31 at 5 36 40 PM" src="https://user-images.githubusercontent.com/66780/215899432-a6cee788-239c-4b2d-9911-ad39863b73dd.png">

**Comment by MatkoKardum** [comment]
Yes i Did and when i download my course videos i go to my folders on my phone but cant find them, that is my problem!!!

**Comment by dachev** [comment]
@MatkoKardum it sounds like you are asking for a different feature. Why do you need the files?

**Comment by MatkoKardum** [comment]
I need to access my files so i can switch them from device to device.

**Comment by MatkoKardum** [comment]
I have multiple

**Comment by MatkoKardum** [comment]
@dachev

**Comment by MatkoKardum** [comment]
@dachev will that be a feature?

**Comment by dachev** [comment]
@MatkoKardum we are probably not going to implement anything like this in the foreseeable future. What kind of device are you thinking of? Do you have something where the FEM app is not available?

**Comment by MatkoKardum** [comment]
I have a linux phone @dachev

**Comment by dachev** [comment]
@MatkoKardum I'm sorry we don't currently support anything outside iOS and android. Can you post a link to the phone's website? I want to take a look at their developer docs and maybe we'll consider a linux app in the future.

**Comment by MatkoKardum** [comment]
@dachev https://www.pine64.org/pinephone/

**Comment by dachev** [comment]
@MatkoKardum we'll keep Linux in mind next time we discuss expansion into new platforms. Thanks for brining this up to our attention.

**Comment by dachev** [comment]
Storing downloads in external storage is now supported.
