### ISSUE TITLE
Unable to download videos for offline viewing on Android app.

### ISSUE THREAD

**Issue by CtripleU** [FrontendMasters/android-issues#46]
When the download icon is tapped, it shows a circle but never moves. Tried several times.

**Comment by dachev** [comment]
@CtripleU Please email us at support@frontendmasters.com or get in touch from the Help menu option in the app, and we would love to assist you.

**Comment by CtripleU** [comment]
Hello,

I already sent a mail to support and was instructed to add this issue on
github.

**Comment by oluwatobiloba2000** [comment]
I am also having the same issue, I cannot download courses, the circle icon does not move.

**Comment by dachev** [comment]
We revamped video downloads last year so this issue is most likely obsolete.
