### ISSUE TITLE
problems with full-screen mode

### ISSUE THREAD

**Issue by paragkatoch** [FrontendMasters/android-issues#47]
There should be a video title over the video screen, right now when I am watching in full-screen mode, there is no way I can know the video title without turning off the full-screen mode.

Also when I turn off the full-screen mode, the list of lesson scrolls from the start to the current lesson, **Is that needed ?**, just showing the current lesson I am on instead of doing a scroll animation would be a good user experience.

And, when I am in full-screen mode, isn't pressing the back button is supposed to turn off the full-screen mode instead of exiting from the course and taking me to the home screen?

**Comment by kaivalya22** [comment]
Same issue. It's so annoying

**Comment by dachev** [comment]
@preIdiot scrolling and back button interaction have been fixed. Feel free to create a new issue about the title suggestion.
