### ISSUE TITLE
Course videos are not playing. Video player is just loading the spinner. Changed password. Updated the app. Still not working.

Web platform is working fine. 

### ISSUE THREAD

**Issue by mhasanrabbi** [FrontendMasters/android-issues#48]
I am facing the issue for two days. It's working with the mobile browser with same wifi network. But in the app it's just loading.

**Comment by dachev** [comment]
@mhasanrabbi is this still happening with the latest release?

**Comment by mhasanrabbi** [comment]
> @mhasanrabbi is this still happening with the latest release?

Thanks. It's fixed now.
