### ISSUE TITLE
Switching Back To App Video Does Not Play

### ISSUE THREAD

**Issue by toreylittlefield** [FrontendMasters/android-issues#49]
Updated to lastest Android version recently: 1.20.2.

Phone on Android 10.

Does not occur consistently, but noticed after updating the app I encounter this bug when switching back to the app and have a video playing. The video player will be a black screen with no controls. I have to exit the course and then press continuing watching to start playing the video again.

![Screenshot_2021-11-25-07-22-40-185_in mjg frontendmasters store](https://user-images.githubusercontent.com/52614742/143324907-29df08ed-71b6-48c4-a74a-cec3e39f81b4.jpg)

**Comment by dachev** [comment]
@toreylittlefield  this should be fixed in the latest release
