### ISSUE TITLE
Video time lapse doesn't work 

### ISSUE THREAD

**Issue by pravavlo** [FrontendMasters/android-issues#50]
Menu button doesn't work to speed time

**Comment by dachev** [comment]
@pravavlo The playback speed selector is working for me. What is your device? What is your app and android version?

**Comment by pravavlo** [comment]
my device is Huawei Y7 prime.. frontend masters is the app....android version is 8.0.0

**Comment by dachev** [comment]
@pravavlo just to be sure, are you referring to the video speed selector?

**Comment by pravavlo** [comment]
yes...video speed is exactly what I was referring to
