### ISSUE TITLE
Cannot cast from android app to google chrome cast or philips tv with integrated chromecast.

### ISSUE THREAD

**Issue by Arjen-1** [FrontendMasters/android-issues#51]
It keeps spinning / loading for ever.
tried multiple chromecast devices. bug happens with all of them.
Other android apps i use are able to cast to the chromecasts without a problem.

**Comment by dachev** [comment]
Hi @Arjen-1. We are in the process of making a new release. I'll ping you when it become available in the next few days.

**Comment by Arjen-1** [comment]
That would be awesome. When is the expected appstore / playstore update?

Outlook voor Android<https://aka.ms/AAb9ysg> downloaden
________________________________

**Comment by dachev** [comment]
@Arjen-1 You should be able to download 1.21.2 by Monday or Tuesday at the latest.

**Comment by Arjen-1** [comment]
Thanks. Can't check it right now. But will get back to you soon.

Cheers

Outlook voor Android<https://aka.ms/AAb9ysg> downloaden
________________________________

**Comment by dachev** [comment]
@Arjen-1 This should be fixed now
