### ISSUE TITLE
Cannot resume an active course video when I minimize the android app and return.

### ISSUE THREAD

**Issue by Innocent9712** [FrontendMasters/android-issues#52]
Whenever I'm on a course and I minimize the app for more than a miniute, I come back to a blank video screen and have to close the course and open it again.

**Comment by dachev** [comment]
Hi @Innocent9712 We are in the process of making a new release. I'll ping you when it become available in the next few days.

**Comment by dachev** [comment]
@Innocent9712 This should be fixed.
