### ISSUE TITLE
Feature Request: Android TV Support

### ISSUE THREAD

**Issue by cecilphillip** [FrontendMasters/android-issues#54]
On Android TV, I'm able to install a variety of video streaming apps which makes it convenient to switch from my laptop/phone/tablet to a larger screen. I do this today with some other video learning apps.

I tried doing this with the Frontend masters app, but it's not supported. This feature would be very a useful boost to my flow as it makes coding along easier since I'd have a larger screen and also would have freed up my laptop.

**Comment by 1Marc** [comment]
We don't have an Android TV standalone app, but you are currently able to use the app on your Android or iOS phone or tablet to stream out to the TV.

**Comment by 1Marc** [comment]
We currently don't have an Android TV standalone app, but you still can play videos to your TV! Simply download the Frontend Masters app onto an Android or iOS phone or tablet, then you are able to airplay/stream it from your phone to the TV.

**Comment by cecilphillip** [comment]
@1Marc I never notice that casting was available. I'll give that a try.
Also, you don't need a standalone app for Android TV. You can add support in an existing app if that's something you'd want to do => https://developer.android.com/training/tv/start/start
