### ISSUE TITLE
Bug: Unable to log in on tablet device

### ISSUE THREAD

**Issue by leonardolombardi07** [FrontendMasters/android-issues#55]
Device: Samsung Galaxy Tab S6 Lite, Android version 12.0

**Steps to Reproduce**
1. Try to log in on tablet
2. See the error message "Failed to login. Please try again.", even though the credentials are right

**Additional Information**
1. Successfully log in with the same credentials through the browser (on the computer and on the tablet) and through the android app on a mobile phone
2. Verified multiple times if the credentials were right while logging in on tablet device
3. Tried to log out from the account on all devices before loggin in on tablet device (maybe there's a limit?)

**Comment by brentmn** [comment]
@leonardolombardi07 , after checking the logs, it looks like the clock on your tablet might be off. That might be corrupting the request signature.

**Comment by leonardolombardi07** [comment]
Yes, the "Date and Hour" part of my tablet was set to "manual". Now it is "automatic" and I was able to log in. Thanks
