### ISSUE TITLE
Casting not working for half of the videos of each course

### ISSUE THREAD

**Issue by learnmlcolab** [FrontendMasters/android-issues#57]
I'm using the cast feature to cast to my chromecast

I'm able to watch about the first half of each course, the rest is not working.

For example, in [this course](https://frontendmasters.com/courses/design-process/), I'm able to watch from the beginning to the [Prototyping Phase](https://frontendmasters.com/courses/design-process/prototyping-phase/) video, I could not watch the rest of the videos.

**Comment by dachev** [comment]
Hi @learnmlcolab. Thanks for the heads up. What happens if you quit Chromecast, skip forward to [Prototyping Phase](https://frontendmasters.com/courses/design-process/prototyping-phase/) locally, and then try to cast again?

**Comment by learnmlcolab** [comment]
Hi @dachev, that's what I did to find the first video that doesn't work. I opened a random video near the end and did binary search until I found the first one that I couldn't cast: [Build & Live Phases](https://frontendmasters.com/courses/design-process/build-live-phases/) (the one after [Prototyping Phase](https://frontendmasters.com/courses/design-process/prototyping-phase/))

This also happens with other courses, not only this one.

**Comment by dachev** [comment]
@learnmlcolab we need some more information in order to debug this issue. In order to protect your privacy, can you write to `support@frontendmasters.com` and we'll take it from there.

**Comment by dachev** [comment]
@learnmlcolab did you have a chance to connect with out support team via email? We need some more information but we want to protect your privacy.
