### ISSUE TITLE
Offline videos don't work unless I watch first online, then go offline 

### ISSUE THREAD

**Issue by SGudbrandsson** [FrontendMasters/android-issues#59]
I was trying to watch videos during a train ride in France, and was unable to watch downloaded videos.

I had downloaded successfully before and watched offline on a plane ride.

I always got this error today while trying to watch:
![Screenshot_20230726-102011](https://github.com/FrontendMasters/android-issues/assets/1608474/a1be5fab-bce3-4aed-8ee3-e078e1445737)

Later, at a train station, I opened an episode online, then went offline and everything played successfully.

I'm guessing there is either DRM check or phone-home stuff before playing a video, even though it's downloaded offline?

Well, this is something I suggest you fix :)

**Comment by dachev** [comment]
This should be fixed in 1.30.0
