### ISSUE TITLE
Progress is not tracked in the app

### ISSUE THREAD

**Issue by wouthoekstra** [FrontendMasters/android-issues#61]
I am watching a course on an Android phone: Samsung Galaxy S23 with Android 14. I was casting the course to a chromecast, and i've watched through a couple of episodes during which the next episodes automatically started.

After this I think a couple of things went wrong:
- After stopping for a brief while, I wanted to continue where I left off but it started at the first episode again. I was still connected to the same chromecast, but the app on the chromecast stopped (which it does after idling for too long)
- After manually figuring out where I was, I manually checked all the completed episodes after completed. This was undone after a couple of seconds.
- I've disconnected from the chromecast, watched a little bit on my phone, and checked all the previous episodes as completed again. Yet again, this was undone after a couple of seconds.

Currently - a day later - two random episodes are checked as completed: The first episode and an episode 6. I am currently at episode 8. I haven't rewatched those two episodes, although I might have misclicked at episode 6 at some point instead of clicking the completed-checkmark at some point.

Apart from the completed checkmarks, most episodes show no progress in the bar below the episode, except for episode 1, and episode 8 (which is the episode I'm currently at).

**Comment by dachev** [comment]
@kristakoch 1.30.0 (525)

**Comment by kristakoch** [comment]
@dachev, I downloaded the latest version of the staging app and tested:
1. Casted, started a course, played 2 lessons, left the course, reentered the course. Does the player start at the first lesson again?
- Started on the third lesson as expected.

2. Casted, started a course, checked 3 lessons as complete, left and reentered the course. Do the lessons stay complete?
- The first lesson (Introduction in Vanilla JavaScript projects) was checked as complete, but the 2nd and 3rd lessons were not. Tried checking them again, leaving the course, and reentering, but the 2nd and 3rd lessons remained unchecked.

3. Stopped casting, tested the same thing in a different course.
- The result was similar to the previous test in that only the Introduction lesson was marked as complete. 

4. While not casting, watched a lesson on my phone. After finishing, is the progress visible in the progress bar for the lesson, and is the lesson checked as complete?
- After finishing the lesson, there was a completed checkmark but no progress in the bar below the lesson. I left the course and reentered, and the checkmark was not there. The progress bar was empty. 
- I tried watching the lesson one more time and returning to the player. The second time I got a checkmark but still no progress in the progress bar.

**Comment by dachev** [comment]
@kristakoch I uploaded a new staging build. Please try 1.30.0 (527) when you have a chance.

**Comment by kristakoch** [comment]
I'm not near a place where I can cast currently, but I downloaded the latest update for the staging app and re-tested 3 and 4 from my last comment:

3. While not casting, checked the first 3 lessons in a course (Build AI-Powered Apps with OpenAI and Node.js), left the course, reentered, and checked which lessons were complete.
- After marking the first 3 lessons of the course as complete in order, leaving the course, and returning, only the 3rd lesson (Intro to LLMs) had the completed checkbox visible. The progress bar was not filled in for any (guessing this might be the desired state, though, for marking complete but not watching?).

4. While not casting, watched a full lesson on my phone and then looked at progress indicators.
- The lesson is checked as complete but the progress bar is not filled in. I left the course and came back, and the progress bar was not visible and the lesson checkmark was gone (the lesson was Scaling Chat & AI Temperature).

**Comment by dachev** [comment]
@kristakoch can you give the new build a try: 1.30.0 (528). I added some extra logging so I'm hoping you will be able to reproduce. Please restart the app to give it a chance to upload the logs.

**Comment by kristakoch** [comment]
@dachev, I updated and restarted the staging app to test, and when I check lessons as complete the app crashes

**Comment by dachev** [comment]
@kristakoch sorry about that, please try 1.30.0 (529)

**Comment by kristakoch** [comment]
@dachev that worked! I was able to go through and check some lessons as complete, and then closed the app. 

Just as a note, I still wasn't seeing checkmarks sticking for the most part, but it does seem consistent that if I go to a video, scrub forward, and then check that video as complete, the check sticks when I return to the player. In case that's a useful clue.

**Comment by kristakoch** [comment]
Can confirm after looking at the debug logging on the server: when watching Get Kids into Coding with Scratch, I checked the lesson Movement Direction & Looks as complete, the event details I expected came in and the record was stored, but the checkmark isn't there for the lesson when I visit the course now.

**Comment by dachev** [comment]
@kristakoch do you mind sharing your staging credentials. If that's ok with you, can you find a lesson hash in the DB that has a completed record but that doesn't show as complete in the app. Basically, I want to login as you, and examine the API server responses.

**Comment by dachev** [comment]
This should be fixed in 1.30.0
