### ISSUE TITLE
[Feature Request] Cancel All button to cancel all started downloads

### ISSUE THREAD

**Issue by sb7896** [FrontendMasters/android-issues#9]
It would be nice to have a **Cancel All** button just like the **Download All** button we have. When I click on Download All button it starts downloading all the videos, but if due to some unforeseen reason any video fails to download, it doesn't start downloading automatically. I have to manually click on **delete** (_cross_) button for every **failed** video. It would be nice to have **Cancel All** button to cancel downloading of all videos.

**Comment by dachev** [comment]
@sb7896 I believe this is fixed.
